### ISSUE TITLE
RuntimeError: CUDA error: invalid device ordinal

### ISSUE THREAD

**Issue by gjkaur** [NiftyTorch/NiftyTorch.v.0.1#1]
I am trying to run Segmentation example using Unet on Google colab with GPU environment. How to handle this runtime error on google colab "RuntimeError: CUDA error: invalid device ordinal".

**Comment by gjkaur** [comment]
Resolved 
pip install niftytorch==0.1.1 --extra-index-url=https://test.pypi.org/simple/

**Comment by NiftyTorch** [comment]
Thanks Gurinderjeet for adding the fix. Just adding that any version >= 0.1.1 will not have that issue.
